Repository ReadyItGo-A-level/Backend, pull requests merged in 2022-09, with the labels that each got.

#30 [feat] - 술 스크랩
  src/main/java/com/alevel/backend/controller/AlcoholController.java
  src/main/java/com/alevel/backend/controller/ExceptionController.java
  src/main/java/com/alevel/backend/controller/MypageCommentController.java
  src/main/java/com/alevel/backend/controller/PostController.java
  src/main/java/com/alevel/backend/controller/PreferenceController.java
  src/main/java/com/alevel/backend/controller/UserController.java
  src/main/java/com/alevel/backend/controller/dto/MypageAccountResponseDto.java
  src/main/java/com/alevel/backend/domain/response/DefaultResponse.java
  src/main/java/com/alevel/backend/domain/response/ResponseMessage.java
  src/main/java/com/alevel/backend/domain/response/ResultResponse.java
  src/main/java/com/alevel/backend/domain/scrapalcohol/ScrapAlcohol.java
  src/main/java/com/alevel/backend/domain/scrapalcohol/ScrapAlcoholRepository.java
  src/main/java/com/alevel/backend/exception/DuplicatedEmailException.java
  src/main/java/com/alevel/backend/exception/DuplicatedUserException.java
  src/main/java/com/alevel/backend/exception/InvalidatePasswordException.java
  src/main/java/com/alevel/backend/exception/InvalidateUserException.java
  src/main/java/com/alevel/backend/exception/WithdrawnUserException.java
  src/main/java/com/alevel/backend/service/AlcoholService.java
  src/main/java/com/alevel/backend/service/UserService.java
Labels: Feature

#34 [feat] - 마이페이지 탭
  src/main/java/com/alevel/backend/controller/MypageTabController.java
  src/main/java/com/alevel/backend/controller/dto/MypageTabDto.java
  src/main/java/com/alevel/backend/domain/comment/Comment.java
  src/main/java/com/alevel/backend/domain/comment/CommentRepository.java
  src/main/java/com/alevel/backend/domain/post/Post.java
  src/main/java/com/alevel/backend/domain/post/PostMapping.java
  src/main/java/com/alevel/backend/domain/post/PostRepository.java
  src/main/java/com/alevel/backend/domain/scrapalcohol/ScrapAlcohol.java
  src/main/java/com/alevel/backend/domain/scrapalcohol/ScrapAlcoholRepository.java
  src/main/java/com/alevel/backend/domain/scrappost/ScrapPost.java
  src/main/java/com/alevel/backend/domain/scrappost/ScrapPostRepository.java
  src/main/java/com/alevel/backend/domain/user/UserRepository.java
  src/main/java/com/alevel/backend/service/MypageTabService.java
Labels: Feature

#39 [feat] 알콜 검색 기능 구현
  src/main/java/com/alevel/backend/controller/AlcoholController.java
  src/main/java/com/alevel/backend/controller/AlcoholSearchController.java
  src/main/java/com/alevel/backend/domain/alcohol/AlcoholRepository.java
  src/main/java/com/alevel/backend/service/AlcoholSearchService.java
  src/main/java/com/alevel/backend/service/SearchService.java
  src/main/resources/application.properties
Labels: Feature

#41 [setting] - Github Action 적용
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  deploy.sh
Labels: setting

#43 [refactor] - 술 전체 조회 시 술 데이터만 출력
  src/main/java/com/alevel/backend/controller/AlcoholController.java
  src/main/java/com/alevel/backend/controller/dto/AlcoholResponseDto.java
  src/main/java/com/alevel/backend/domain/alcohol/AlcoholRepositoryCustom.java
  src/main/java/com/alevel/backend/domain/alcohol/AlcoholRepositoryCustomImpl.java
  src/main/java/com/alevel/backend/service/AlcoholService.java
Labels: refactor

#46 [refactor] - 술 추천 페이지
  src/main/java/com/alevel/backend/controller/AlcoholController.java
  src/main/java/com/alevel/backend/controller/ExceptionController.java
  src/main/java/com/alevel/backend/controller/PostController.java
  src/main/java/com/alevel/backend/controller/PreferenceController.java
  src/main/java/com/alevel/backend/controller/ReviewController.java
  src/main/java/com/alevel/backend/controller/dto/AlcoholResponseDto.java
  src/main/java/com/alevel/backend/controller/dto/AlcoholReviewDto.java
  src/main/java/com/alevel/backend/controller/dto/AlcoholReviewRequestDto.java
  src/main/java/com/alevel/backend/controller/dto/AlcoholReviewResponseDto.java
  src/main/java/com/alevel/backend/controller/dto/AlcoholReviewSaveDto.java
  src/main/java/com/alevel/backend/controller/dto/MyPagePostResponseDto.java
  src/main/java/com/alevel/backend/controller/dto/PostResponseDto.java
  src/main/java/com/alevel/backend/domain/BaseTimeEntity.java
  src/main/java/com/alevel/backend/domain/alcohol/AlcoholRepository.java
  src/main/java/com/alevel/backend/domain/likepost/LikePost.java
  src/main/java/com/alevel/backend/domain/post/Post.java
  src/main/java/com/alevel/backend/domain/post/PostRepository.java
  src/main/java/com/alevel/backend/domain/response/ResponseMessage.java
  src/main/java/com/alevel/backend/domain/review/ReviewRepository.java
  src/main/java/com/alevel/backend/domain/scrappost/ScrapPost.java
  src/main/java/com/alevel/backend/exception/InvalidatePostException.java
  src/main/java/com/alevel/backend/exception/InvalidateReviewException.java
  src/main/java/com/alevel/backend/service/AlcoholService.java
  src/main/java/com/alevel/backend/service/PostService.java
  src/main/java/com/alevel/backend/service/PreferenceService.java
  src/main/java/com/alevel/backend/service/ReviewService.java
Labels: Feature, refactor
